version: '3'

services:
    php:
        build:
            context: .
            dockerfile: ./php.Dockerfile
            args:
                USER_ID: ${USER_ID-1000}
        restart: always
        working_dir: /var/www/html
        tty: true
        ports:
            -   '8000:8000'
        expose:
            -   8000
        volumes:
            -   ./:/var/www/html
        depends_on:
            - mysql
        networks:
            platform-net:
                ipv4_address: 172.24.0.6

    node:
        build:
            context: .
            dockerfile: ./node.Dockerfile
        tty: true
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            platform-net:
                ipv4_address: 172.24.0.2

    mysql:
        image: mysql:8.0.31
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - ./storage/data/mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: filament_dashboard
            MYSQL_ROOT_PASSWORD: password
        networks:
            platform-net:
                ipv4_address: 172.24.0.3

networks:
    platform-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.0.0/24
        driver_opts:
            com.docker.network.bridge.name: fil-network
