<?php

namespace App\Tables\Columns;

use Filament\Tables\Columns\Column;

class AgreementColumn extends Column
{
    protected string $view = 'tables.columns.agreement-column';

    public function viewData(array $data): static
    {
        return parent::viewData($data); // TODO: Change the autogenerated stub
    }
}
